POST http://localhost:8080/visita HTTP/1.1
Content-Type: application/json

{
    "clienteId": 10,
    "fechaProgramada": "2020-12-11T09:00:00",
    "direccion": "Oficina del cliente ubicada en la ciudad de Monterrey",
    "proposito": "Mostrarle unos productos",
    "vendedor": "Araceli García"
}